debug: false

spring:
  jpa:
    properties.hibernate.jdbc.lob.non_contextual_creation: true
    properties.hibernate.jdbc.batch_size: 2
    hibernate.ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false

  datasource:
      url: jdbc:postgresql://localhost:54320/headerSV
      username: headerSV
      password: test
      driverClassName: org.postgresql.Driver


# Application Configuration:
headersv:
  # This variable will determine what Repositories are loaded into the Spring context (postgresql or the mongodb ones)
  persistenceEngine: postgresql

  # Listener Configuration params:
  p2p:
    maxPeers: 100
    minPeers: 20
    relayTxs: false

  sync:
    headersToIgnore: 00000000000000000019f1679932c8a69051fca08d0934ac0c6cad56077d0c66, 0000000000000000004626ff6e3b936941d341c5932ece4357eeccac44e6d56c
    requestHeadersRefreshIntervalMs: 30000


  propagation:
    buffer:
      enabled: true
      threads: 1
      bufferSize: 1000000
    persistence:
      peer:
        enabled: false
        batchSize: 20000
      block:
        enabled: true
        batchSize: 20000
