# Application Configuration:
headersv:
  # Listener Configuration params:
  network:
    networkId: "regtest"
    minPeers: 1
    maxPeers: 15
    peers: "127.0.0.1"
    port: 18444


  sync:
    headersToIgnore:

  storage:
    pruning:
      fork:
        enabled: false
        pruneAfterConfirmations: 7
      orphan:
        enabled: false
        pruneAfterInterval: 600