# Application Configuration:
headersv:
  # Listener Configuration params:
  network:
    networkId: "testnet"
    minPeers: 5
    maxPeers: 10

  sync:
    headersToIgnore:
    powLimit: 00000000ffffffffffffffffffffffffffffffffffffffffffffffffffffffff

  storage:
    pruning:
      fork:
        enabled: false
        pruneAfterConfirmations: 7
      orphan:
        enabled: false
        pruneAfterInterval: 600
