debug: false

spring:
  jpa:
    properties.hibernate.jdbc.lob.non_contextual_creation: true
    properties.hibernate.jdbc.batch_size: 25
    hibernate.ddl-auto: update
    show-sql: false

  datasource:
      url: jdbc:postgresql://localhost:54320/headerSV
      username: headerSV
      password: test
      driverClassName: org.postgresql.Driver


# Application Configuration:
headersv:
  # This variable will determine what Repositories are loaded into the Spring context (postgresql or the mongodb ones)
  persistenceEngine: postgresql

  # Listener Configuration params:
  listener-app:
    listener:
      p2p:
        folders:
          data: /workspace/headerSV/src/main/resources/data
          config:
        maxPeers: 25
        minPeers: 10
        relayTxs: true
      height-locator:
        topChainMargin: 0
        minPeersNeeded: 10

    propagation:
      buffer:
        enabled: true
        threads: 6
        bufferSize: 10000
      persistence:
        peer:
          enabled: true
          batchSize: 1
        block:
          enabled: true
          batchSize: 1
        tx:
          enabled: true
          batchSize: 100
    metrics:
      peers:
        enabled: true
        frequencyInMillis: 10000
      txs:
        enabled: true
        frequencyInMillis: 5000
      messages:
        enabled: true
        frequencyInMillis: 5000
      inv-size:
        enabled: true
        frequencyInMillis: 5000
      kbytes:
        enabled: true
        frequencyInMillis: 5000
